# Generated by Django 4.2.7 on 2025-10-27 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biografia')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Data de contratação')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('theme_preference', models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro'), ('auto', 'Automático')], default='auto', max_length=10, verbose_name='Tema preferido')),
                ('language_preference', models.CharField(choices=[('pt-br', 'Português'), ('en', 'English')], default='pt-br', max_length=10, verbose_name='Idioma preferido')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notificações por email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis dos Usuários',
                'db_table': 'user_profiles',
            },
        ),
    ]
