# Generated by Django 4.2 on 2025-10-27 13:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('order_index', models.IntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'db_table': 'modules',
                'ordering': ['order_index', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='Duração (minutos)')),
                ('order_index', models.IntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Treinamento',
                'verbose_name_plural': 'Treinamentos',
                'db_table': 'trainings',
                'ordering': ['order_index', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_code', models.CharField(default=uuid.uuid4, max_length=50, unique=True, verbose_name='Código do Certificado')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Emitido em')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'db_table': 'user_certificates',
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_seconds', models.IntegerField(default=0, verbose_name='Progresso (segundos)')),
                ('completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('last_watched', models.DateTimeField(auto_now=True, verbose_name='Última visualização')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
            ],
            options={
                'verbose_name': 'Progresso do Usuário',
                'verbose_name_plural': 'Progressos dos Usuários',
                'db_table': 'user_progress',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('youtube_url', models.URLField(max_length=500, verbose_name='URL do YouTube')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='Duração (segundos)')),
                ('order_index', models.IntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.training', verbose_name='Treinamento')),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
                'db_table': 'videos',
                'ordering': ['order_index', 'title'],
            },
        ),
    ]
