# Generated by Django 4.2 on 2025-10-27 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.video', verbose_name='Vídeo'),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.training', verbose_name='Treinamento'),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='training',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='courses.module', verbose_name='Módulo'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['category'], name='modules_categor_a75ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['order_index'], name='modules_order_i_65cb7c_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['training_id'], name='videos_trainin_e97b60_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['order_index'], name='videos_order_i_d37cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user_id'], name='user_progre_user_id_77f83f_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['video_id'], name='user_progre_video_i_aebfa7_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['completed'], name='user_progre_complet_9918bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'video')},
        ),
        migrations.AddIndex(
            model_name='usercertificate',
            index=models.Index(fields=['user_id'], name='user_certif_user_id_a821af_idx'),
        ),
        migrations.AddIndex(
            model_name='usercertificate',
            index=models.Index(fields=['training_id'], name='user_certif_trainin_2f59d8_idx'),
        ),
        migrations.AddIndex(
            model_name='usercertificate',
            index=models.Index(fields=['certificate_code'], name='user_certif_certifi_9ada28_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercertificate',
            unique_together={('user', 'training')},
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['module_id'], name='trainings_module__db79b9_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['order_index'], name='trainings_order_i_4bf0b0_idx'),
        ),
    ]
